---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: jg-abitti-kiosk
# description will be included in the image's metadata
description: Kiosk image for exam supervision — cage compositor + Chromium, tmpfs home, auto-login

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: dnf
    install:
      packages:
        - chromium
        - cage
        - udiskie
        - swayidle
    remove:
      packages:
        - firefox
        - firefox-langpacks
        - gnome-initial-setup
        - gnome-tour
        - gnome-software
        - nautilus
        - gnome-console
        - gnome-text-editor
        - evince
        - gnome-calculator
        - micro
        - starship

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: systemd
    system:
      enabled:
        - var-home-kiosk.mount
        - kiosk-accounts.service
        - kiosk-setup.service
      masked:
        - home-kiosk.mount
        - flatpak-system-update.timer
    user:
      disabled:
        - flatpak-user-update.timer
      masked:
        - gnome-keyring-daemon.service

  - type: default-flatpaks
    configurations:
      - notify: false
        scope: system
        remove:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - org.gnome.Calculator
          - org.gnome.Calendar
          - org.gnome.Characters
          - org.gnome.Clocks
          - org.gnome.Connections
          - org.gnome.Contacts
          - org.gnome.Evince
          - org.gnome.Fonts
          - org.gnome.Logs
          - org.gnome.Maps
          - org.gnome.Music
          - org.gnome.Photos
          - org.gnome.Snapshot
          - org.gnome.TextEditor
          - org.gnome.Totem
          - org.gnome.Weather
          - org.gnome.baobab
      - scope: user

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
